import 'dart:io';

import 'package:flutter_skill_gen/src/ci/git_hooks_installer.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('GitHooksInstaller', () {
    late Directory tempDir;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync(
        'flutter_skill_gen_hooks_test_',
      );
    });

    tearDown(() {
      if (tempDir.existsSync()) {
        tempDir.deleteSync(recursive: true);
      }
    });

    /// Creates a fake .git directory so the installer treats
    /// the temp dir as a git repo.
    void initFakeGit() {
      Directory(p.join(tempDir.path, '.git')).createSync(recursive: true);
    }

    group('hookScript', () {
      test('pre-commit script checks staged files', () {
        final script = GitHooksInstaller.hookScript('pre-commit');
        expect(script, startsWith('#!/bin/sh'));
        expect(script, contains('git diff --cached'));
        expect(script, contains('flutter_skill_gen sync --ci'));
      });

      test('post-merge script runs sync', () {
        final script = GitHooksInstaller.hookScript('post-merge');
        expect(script, startsWith('#!/bin/sh'));
        expect(script, contains('flutter_skill_gen sync --ci'));
      });

      test('scripts contain auto-generated marker', () {
        for (final hook in GitHooksInstaller.supportedHooks) {
          final script = GitHooksInstaller.hookScript(hook);
          expect(script, contains('Auto-generated by flutter_skill_gen'));
        }
      });
    });

    group('hooksDir', () {
      test('returns null when no .git directory', () {
        expect(GitHooksInstaller.hooksDir(tempDir.path), isNull);
      });

      test('returns path when .git directory exists', () {
        initFakeGit();
        final dir = GitHooksInstaller.hooksDir(tempDir.path);
        expect(dir, isNotNull);
        expect(dir, endsWith('.git/hooks'));
      });
    });

    group('installHook', () {
      test('returns false for unsupported hook name', () {
        initFakeGit();
        final result = GitHooksInstaller.installHook(
          projectPath: tempDir.path,
          hookName: 'unknown-hook',
        );
        expect(result, isFalse);
      });

      test('returns false when not a git repo', () {
        final result = GitHooksInstaller.installHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );
        expect(result, isFalse);
      });

      test('installs pre-commit hook', () {
        initFakeGit();
        final result = GitHooksInstaller.installHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );
        expect(result, isTrue);

        final hookFile = File(
          p.join(tempDir.path, '.git', 'hooks', 'pre-commit'),
        );
        expect(hookFile.existsSync(), isTrue);
        expect(hookFile.readAsStringSync(), contains('flutter_skill_gen'));
      });

      test('installs post-merge hook', () {
        initFakeGit();
        final result = GitHooksInstaller.installHook(
          projectPath: tempDir.path,
          hookName: 'post-merge',
        );
        expect(result, isTrue);

        final hookFile = File(
          p.join(tempDir.path, '.git', 'hooks', 'post-merge'),
        );
        expect(hookFile.existsSync(), isTrue);
      });

      test('backs up existing non-flutter_skill_gen hook', () {
        initFakeGit();
        final hooksDir = p.join(tempDir.path, '.git', 'hooks');
        Directory(hooksDir).createSync(recursive: true);

        final hookPath = p.join(hooksDir, 'pre-commit');
        File(hookPath).writeAsStringSync('#!/bin/sh\necho "custom hook"');

        GitHooksInstaller.installHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );

        final backup = File('$hookPath.backup');
        expect(backup.existsSync(), isTrue);
        expect(backup.readAsStringSync(), contains('custom hook'));
      });

      test('does not back up existing flutter_skill_gen hook', () {
        initFakeGit();
        // Install once.
        GitHooksInstaller.installHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );

        // Install again — should not create .backup.
        GitHooksInstaller.installHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );

        final backup = File(
          p.join(tempDir.path, '.git', 'hooks', 'pre-commit.backup'),
        );
        expect(backup.existsSync(), isFalse);
      });
    });

    group('installAll', () {
      test('installs all supported hooks', () {
        initFakeGit();
        final results = GitHooksInstaller.installAll(projectPath: tempDir.path);

        expect(results, hasLength(2));
        expect(results['pre-commit'], isTrue);
        expect(results['post-merge'], isTrue);
      });
    });

    group('removeHook', () {
      test('removes installed flutter_skill_gen hook', () {
        initFakeGit();
        GitHooksInstaller.installHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );

        final removed = GitHooksInstaller.removeHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );
        expect(removed, isTrue);

        final hookFile = File(
          p.join(tempDir.path, '.git', 'hooks', 'pre-commit'),
        );
        expect(hookFile.existsSync(), isFalse);
      });

      test('does not remove non-flutter_skill_gen hook', () {
        initFakeGit();
        final hooksDir = p.join(tempDir.path, '.git', 'hooks');
        Directory(hooksDir).createSync(recursive: true);

        File(
          p.join(hooksDir, 'pre-commit'),
        ).writeAsStringSync('#!/bin/sh\necho "custom"');

        final removed = GitHooksInstaller.removeHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );
        expect(removed, isFalse);
      });

      test('restores backup after removal', () {
        initFakeGit();
        final hooksDir = p.join(tempDir.path, '.git', 'hooks');
        Directory(hooksDir).createSync(recursive: true);

        // Create a custom hook, then install over it.
        File(
          p.join(hooksDir, 'pre-commit'),
        ).writeAsStringSync('#!/bin/sh\necho "original"');
        GitHooksInstaller.installHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );

        // Remove — should restore the backup.
        GitHooksInstaller.removeHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );

        final hookFile = File(p.join(hooksDir, 'pre-commit'));
        expect(hookFile.existsSync(), isTrue);
        expect(hookFile.readAsStringSync(), contains('original'));
      });

      test('returns false when hook does not exist', () {
        initFakeGit();
        final removed = GitHooksInstaller.removeHook(
          projectPath: tempDir.path,
          hookName: 'pre-commit',
        );
        expect(removed, isFalse);
      });
    });

    group('status', () {
      test('shows all hooks as not installed initially', () {
        initFakeGit();
        final result = GitHooksInstaller.status(projectPath: tempDir.path);
        expect(result['pre-commit'], isFalse);
        expect(result['post-merge'], isFalse);
      });

      test('shows installed hooks correctly', () {
        initFakeGit();
        GitHooksInstaller.installAll(projectPath: tempDir.path);

        final result = GitHooksInstaller.status(projectPath: tempDir.path);
        expect(result['pre-commit'], isTrue);
        expect(result['post-merge'], isTrue);
      });

      test('returns all false when not a git repo', () {
        final result = GitHooksInstaller.status(projectPath: tempDir.path);
        for (final v in result.values) {
          expect(v, isFalse);
        }
      });
    });
  });
}
