import 'dart:io';

import 'package:flutter_skill_gen/src/ci/github_action_generator.dart';
import 'package:test/test.dart';

void main() {
  group('GitHubActionGenerator', () {
    group('generate', () {
      test('starts with auto-generated comment', () {
        final yaml = GitHubActionGenerator.generate();
        expect(yaml, startsWith('# Auto-generated by flutter_skill_gen'));
      });

      test('contains workflow name', () {
        final yaml = GitHubActionGenerator.generate();
        expect(yaml, contains('name: Sync SKILL.md'));
      });

      test('triggers on push to lib/, pubspec, and test/', () {
        final yaml = GitHubActionGenerator.generate();
        expect(yaml, contains("- 'lib/**'"));
        expect(yaml, contains("- 'pubspec.yaml'"));
        expect(yaml, contains("- 'test/**'"));
      });

      test('uses flutter-action by default', () {
        final yaml = GitHubActionGenerator.generate();
        expect(yaml, contains('subosito/flutter-action'));
      });

      test('uses dart-only when usesFlutter is false', () {
        final yaml = GitHubActionGenerator.generate(usesFlutter: false);
        expect(yaml, contains('dart-lang/setup-dart'));
        expect(yaml, isNot(contains('subosito/flutter-action')));
      });

      test('installs flutter_skill_gen via pub global', () {
        final yaml = GitHubActionGenerator.generate();
        expect(yaml, contains('dart pub global activate flutter_skill_gen'));
      });

      test('runs sync with --ci flag', () {
        final yaml = GitHubActionGenerator.generate();
        expect(yaml, contains('flutter_skill_gen sync --ci'));
      });

      test('includes API key secret reference', () {
        final yaml = GitHubActionGenerator.generate();
        expect(yaml, contains('FLUTTER_SKILL_API_KEY'));
      });

      test('uses git-auto-commit-action', () {
        final yaml = GitHubActionGenerator.generate();
        expect(yaml, contains('git-auto-commit-action'));
      });

      test('commit message mentions SKILL.md', () {
        final yaml = GitHubActionGenerator.generate();
        expect(yaml, contains('chore: sync SKILL.md files'));
      });
    });

    group('write', () {
      late Directory tempDir;

      setUp(() {
        tempDir = Directory.systemTemp.createTempSync(
          'flutter_skill_gen_action_test_',
        );
      });

      tearDown(() {
        if (tempDir.existsSync()) {
          tempDir.deleteSync(recursive: true);
        }
      });

      test('writes workflow file to .github/workflows/', () {
        final path = GitHubActionGenerator.write(projectPath: tempDir.path);

        expect(File(path).existsSync(), isTrue);
        expect(path, contains('.github'));
        expect(path, contains('workflows'));
        expect(path, endsWith('skill_sync.yml'));
      });

      test('creates parent directories', () {
        final path = GitHubActionGenerator.write(projectPath: tempDir.path);

        expect(File(path).existsSync(), isTrue);
      });

      test('file content matches generate output', () {
        final path = GitHubActionGenerator.write(projectPath: tempDir.path);

        final written = File(path).readAsStringSync();
        final expected = GitHubActionGenerator.generate();
        expect(written, expected);
      });
    });
  });
}
