import 'dart:io';

import 'package:path/path.dart' as p;

import '../models/project_facts.dart';
import 'split_planner.dart';

/// Generates a `.skill_manifest.yaml` that maps skill files to their
/// domain scopes, enabling prompt-aware skill injection in Phase 4.
class ManifestGenerator {
  const ManifestGenerator._();

  /// The default output file name.
  static const defaultFileName = '.skill_manifest.yaml';

  /// Generates the manifest YAML content from [facts].
  ///
  /// When [plan] is provided, the manifest references exactly the
  /// skill files the plan will produce — this keeps the manifest
  /// truthful for layouts where the raw `recommendedSkillFiles`
  /// would list domains that end up empty (e.g. a recommended
  /// `data` scope with no `lib/data` directory). Omit [plan] for
  /// single-file mode or facts-only runs.
  static String generate(ProjectFacts facts, {SkillPlan? plan}) {
    final buf = StringBuffer()
      ..writeln('# Auto-generated by flutter_skill_gen')
      ..writeln(
        '# Maps skill files to domain scopes for '
        'prompt-aware injection.',
      )
      ..writeln()
      ..writeln('skills:')
      // Core skill — always injected.
      ..writeln('  - file: SKILL.md')
      ..writeln('    scope:')
      ..writeln('      - architecture')
      ..writeln('      - conventions')
      ..writeln('      - dependencies');

    if (facts.patterns.routing != null) {
      buf.writeln('      - routing');
    }

    buf.writeln('    always_inject: true');

    // Prefer the plan's scopes when available — they reflect what
    // will actually be written to disk. Fall back to
    // recommendedSkillFiles for callers that don't have a plan.
    final scopes = plan != null
        ? plan.specs.map((s) => s.skillName).toList()
        : (facts.complexity?.recommendedSkillFiles ?? ['core']);
    if (scopes.length > 1) {
      for (final scope in scopes) {
        if (scope == 'core') continue;
        _writeFeatureSkill(buf, scope, facts);
      }
    }

    return buf.toString();
  }

  /// Generates the manifest and writes it to [outputDir].
  ///
  /// Returns the absolute path of the written file.
  static String write(
    ProjectFacts facts, {
    required String outputDir,
    SkillPlan? plan,
  }) {
    final content = generate(facts, plan: plan);
    final outputPath = p.join(outputDir, defaultFileName);
    final file = File(outputPath);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
    return outputPath;
  }

  static void _writeFeatureSkill(
    StringBuffer buf,
    String scope,
    ProjectFacts facts,
  ) {
    buf.writeln();

    final fileName = 'SKILL_$scope.md';
    buf
      ..writeln('  - file: $fileName')
      ..writeln('    scope:');

    final keywords = _scopeKeywords(scope);
    for (final kw in keywords) {
      buf.writeln('      - $kw');
    }

    buf.writeln(
      '    inject_when: prompt mentions '
      '${scope.replaceAll('_', ' ')}-related features',
    );
  }

  /// Returns scope keywords for known domain names.
  static List<String> _scopeKeywords(String scope) {
    return switch (scope) {
      'auth' => [
        'authentication',
        'authorization',
        'login',
        'signup',
        'session',
      ],
      'data' => ['api', 'repository', 'models', 'caching', 'local_storage'],
      'design_system' => [
        'widgets',
        'theming',
        'components',
        'atoms',
        'molecules',
      ],
      'home' => ['home', 'dashboard', 'main_screen'],
      'cart' => ['cart', 'checkout', 'order', 'payment'],
      'profile' => ['profile', 'account', 'settings'],
      'search' => ['search', 'filter', 'query'],
      _ => [scope],
    };
  }
}
