import 'dart:async';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;

import '../../ai/prompt_builder.dart';
import '../../generators/split_planner.dart';
import '../../models/project_facts.dart';
import '../../scanner/project_scanner.dart';
import '../../skill/skill_workspace.dart';
import '../../utils/logger.dart';

/// CLI command that scans a project and writes the prompts an
/// external author needs, without calling any model.
///
/// This is the front half of the `prompt` → write drafts → `assemble`
/// loop that lets Claude Code generate skill files itself, using the
/// credentials it already has rather than an API key.
class PromptCommand extends Command<int> {
  /// Creates a [PromptCommand].
  PromptCommand() {
    argParser
      ..addOption(
        'path',
        abbr: 'p',
        help: 'Path to the Flutter project to analyze.',
        defaultsTo: '.',
      )
      ..addOption(
        'work-dir',
        help:
            'Directory for the prompt/draft handoff. '
            'Defaults to ${SkillWorkspace.defaultDirName}/ inside the '
            'project.',
      )
      ..addFlag(
        'split',
        help:
            'Emit one prompt per feature plus a core prompt. '
            'Auto-detected by default based on project complexity.',
        defaultsTo: null,
      )
      ..addFlag('verbose', abbr: 'v', help: 'Enable verbose logging.');
  }

  @override
  String get name => 'prompt';

  @override
  String get description =>
      'Scan a project and emit the skill-writing prompts for an '
      'external author (no API key, no model call).';

  @override
  FutureOr<int>? run() async {
    final results = argResults!;
    final projectPath = p.normalize(p.absolute(results.option('path')!));
    final verbose = results.flag('verbose');
    final splitFlag = results.wasParsed('split') ? results.flag('split') : null;

    final logger = Logger(verbose: verbose)
      ..info('Analyzing Flutter project at: $projectPath');

    final scanner = ProjectScanner(projectPath: projectPath, logger: logger);
    final facts = scanner.scan();

    if (facts == null) {
      logger.error(
        'Analysis failed. Ensure the path contains a '
        'valid Flutter/Dart project with a pubspec.yaml.',
      );
      return 64;
    }

    const planner = SplitPlanner();
    final plan = planner.plan(
      facts,
      projectPath: projectPath,
      forceSplit: splitFlag,
    );

    final workDir =
        results.option('work-dir') ??
        p.join(projectPath, SkillWorkspace.defaultDirName);
    final workspace =
        SkillWorkspace(directory: p.normalize(p.absolute(workDir)))
          ..reset()
          ..writeFacts(facts)
          ..writePlan(plan, projectPath: projectPath, forceSplit: splitFlag);

    for (final spec in plan.specs) {
      workspace.writePrompt(spec.skillName, _promptFor(spec, facts, plan));
      logger.debug('  Wrote ${workspace.promptPath(spec.skillName)}');
    }

    final scopes = plan.specs.map((s) => s.skillName).join(', ');
    logger
      ..success(
        'Wrote ${plan.specs.length} prompt(s) to '
        '${workspace.promptsDir}',
      )
      ..info('')
      ..info('Scopes: $scopes')
      ..info('')
      ..info('Next:')
      ..info('  1. Read each ${workspace.promptsDir}/<scope>.md')
      ..info('  2. Write your draft to ${workspace.draftsDir}/<scope>.md')
      ..info('  3. Run: flutter_skill_gen assemble');

    return 0;
  }

  /// Renders the prompt file for [spec].
  ///
  /// The system prompt goes first so that a reader who only sees the
  /// start of a long file still gets the rules; the facts payload —
  /// which is the bulk — follows it.
  String _promptFor(SkillSpec spec, ProjectFacts facts, SkillPlan plan) {
    final String systemPrompt;
    final String userMessage;

    if (spec.isDomain && spec.domainFacts != null) {
      systemPrompt = PromptBuilder.domainSystemPrompt;
      userMessage = PromptBuilder.buildDomainMessage(spec.domainFacts!, facts);
    } else if (plan.isSplit) {
      systemPrompt = PromptBuilder.coreSystemPrompt;
      userMessage = PromptBuilder.buildCoreMessage(facts);
    } else {
      systemPrompt = PromptBuilder.systemPrompt;
      userMessage = PromptBuilder.buildUserMessage(facts);
    }

    return '''
<!--
  flutter_skill_gen prompt for scope "${spec.skillName}".
  Write your draft to drafts/${spec.skillName}.md, then run
  "flutter_skill_gen assemble". Do not edit this file.
-->

# Instructions

$systemPrompt

# Input

$userMessage
''';
  }
}
