import 'dart:io';

import 'package:flutter_skill_gen/src/generators/manifest_generator.dart';
import 'package:flutter_skill_gen/src/models/convention_info.dart';
import 'package:flutter_skill_gen/src/models/dependency_info.dart';
import 'package:flutter_skill_gen/src/models/pattern_info.dart';
import 'package:flutter_skill_gen/src/models/project_facts.dart';
import 'package:flutter_skill_gen/src/models/structure_info.dart';
import 'package:test/test.dart';

ProjectFacts _buildFacts({
  PatternInfo patterns = const PatternInfo(),
  ComplexityInfo? complexity,
}) {
  return ProjectFacts(
    projectName: 'test_app',
    dependencies: const DependencyInfo(),
    structure: const StructureInfo(organization: 'feature-first'),
    patterns: patterns,
    conventions: const ConventionInfo(),
    complexity: complexity,
    generatedAt: '2026-04-16T12:00:00Z',
    toolVersion: '0.1.0',
  );
}

void main() {
  group('ManifestGenerator', () {
    group('generate', () {
      test('starts with auto-generated comment', () {
        final yaml = ManifestGenerator.generate(_buildFacts());
        expect(yaml, startsWith('# Auto-generated by flutter_skill_gen'));
      });

      test('contains skills list', () {
        final yaml = ManifestGenerator.generate(_buildFacts());
        expect(yaml, contains('skills:'));
      });

      test('always includes core SKILL.md entry', () {
        final yaml = ManifestGenerator.generate(_buildFacts());
        expect(yaml, contains('file: SKILL.md'));
        expect(yaml, contains('always_inject: true'));
      });

      test('includes architecture scope', () {
        final yaml = ManifestGenerator.generate(_buildFacts());
        expect(yaml, contains('- architecture'));
        expect(yaml, contains('- conventions'));
        expect(yaml, contains('- dependencies'));
      });

      test('includes routing scope when routing detected', () {
        final yaml = ManifestGenerator.generate(
          _buildFacts(patterns: const PatternInfo(routing: 'go_router')),
        );
        expect(yaml, contains('- routing'));
      });

      test('omits routing scope when no routing', () {
        final yaml = ManifestGenerator.generate(_buildFacts());
        // The core skill scope should not contain routing
        // when no routing is detected.
        final lines = yaml.split('\n');
        final coreSection = lines.takeWhile((l) => !l.contains('inject_when'));
        final routingInCore = coreSection.any((l) => l.trim() == '- routing');
        expect(routingInCore, isFalse);
      });

      test('no feature skills for small projects', () {
        final yaml = ManifestGenerator.generate(
          _buildFacts(
            complexity: const ComplexityInfo(
              totalDartFiles: 5,
              totalFeatures: 1,
              estimatedMagnitude: 'small',
              recommendedSkillFiles: ['core'],
            ),
          ),
        );
        expect(yaml, isNot(contains('SKILL_auth.md')));
        expect(yaml, isNot(contains('inject_when')));
      });

      test('generates feature skills for medium/large projects', () {
        final yaml = ManifestGenerator.generate(
          _buildFacts(
            complexity: const ComplexityInfo(
              totalDartFiles: 50,
              totalFeatures: 4,
              estimatedMagnitude: 'medium',
              recommendedSkillFiles: ['core', 'auth', 'home', 'cart'],
            ),
          ),
        );
        expect(yaml, contains('SKILL_auth.md'));
        expect(yaml, contains('SKILL_home.md'));
        expect(yaml, contains('SKILL_cart.md'));
      });

      test('feature skills have inject_when rules', () {
        final yaml = ManifestGenerator.generate(
          _buildFacts(
            complexity: const ComplexityInfo(
              recommendedSkillFiles: ['core', 'auth'],
            ),
          ),
        );
        expect(yaml, contains('inject_when:'));
      });

      test('auth feature has correct scope keywords', () {
        final yaml = ManifestGenerator.generate(
          _buildFacts(
            complexity: const ComplexityInfo(
              recommendedSkillFiles: ['core', 'auth'],
            ),
          ),
        );
        expect(yaml, contains('- authentication'));
        expect(yaml, contains('- login'));
        expect(yaml, contains('- signup'));
      });

      test('unknown feature uses scope name as keyword', () {
        final yaml = ManifestGenerator.generate(
          _buildFacts(
            complexity: const ComplexityInfo(
              recommendedSkillFiles: ['core', 'notifications'],
            ),
          ),
        );
        expect(yaml, contains('SKILL_notifications.md'));
        expect(yaml, contains('- notifications'));
      });
    });

    group('write', () {
      late Directory tempDir;

      setUp(() {
        tempDir = Directory.systemTemp.createTempSync(
          'flutter_skill_gen_manifest_test_',
        );
      });

      tearDown(() {
        if (tempDir.existsSync()) {
          tempDir.deleteSync(recursive: true);
        }
      });

      test('writes manifest file to output directory', () {
        final path = ManifestGenerator.write(
          _buildFacts(),
          outputDir: tempDir.path,
        );

        expect(File(path).existsSync(), isTrue);
        expect(path, endsWith('.skill_manifest.yaml'));
      });

      test('file content matches generate output', () {
        final facts = _buildFacts();
        final path = ManifestGenerator.write(facts, outputDir: tempDir.path);

        final written = File(path).readAsStringSync();
        final expected = ManifestGenerator.generate(facts);
        expect(written, expected);
      });

      test('creates parent directories if needed', () {
        final nestedDir = '${tempDir.path}/nested/deep';
        final path = ManifestGenerator.write(
          _buildFacts(),
          outputDir: nestedDir,
        );

        expect(File(path).existsSync(), isTrue);
      });
    });
  });
}
