import 'dart:io';

import 'package:path/path.dart' as p;

/// Installs git hooks that trigger `flutter_skill_gen sync` on
/// relevant git events.
class GitHooksInstaller {
  const GitHooksInstaller._();

  /// Supported hook names.
  static const supportedHooks = ['pre-commit', 'post-merge'];

  /// Generates the shell script content for a git hook.
  static String hookScript(String hookName) {
    final buf = StringBuffer()
      ..writeln('#!/bin/sh')
      ..writeln('# Auto-generated by flutter_skill_gen — $hookName hook')
      ..writeln('# Re-syncs skill files when project code changes.')
      ..writeln();

    if (hookName == 'pre-commit') {
      buf
        ..writeln(
          '# Check if any lib/ or pubspec.yaml '
          'files are staged.',
        )
        ..writeln(
          'STAGED=\$(git diff --cached --name-only '
          '-- "lib/" "pubspec.yaml" "test/")',
        )
        ..writeln('if [ -z "\$STAGED" ]; then')
        ..writeln('  exit 0')
        ..writeln('fi')
        ..writeln()
        ..writeln(
          'echo "[flutter_skill_gen] '
          'Syncing skill files..."',
        )
        ..writeln('flutter_skill_gen sync --ci')
        ..writeln('RESULT=\$?')
        ..writeln()
        ..writeln('if [ \$RESULT -ne 0 ]; then')
        ..writeln(
          '  echo "[flutter_skill_gen] '
          'Sync failed (exit \$RESULT), '
          'committing anyway."',
        )
        ..writeln('fi')
        ..writeln()
        ..writeln('# Stage any updated skill files.')
        ..writeln(
          'git add -u -- "*.md" ".cursorrules" '
          '".windsurfrules" ".github/copilot-instructions.md" '
          '".agents/" ".gemini/" 2>/dev/null || true',
        )
        ..writeln()
        ..writeln('exit 0');
    } else if (hookName == 'post-merge') {
      buf
        ..writeln(
          'echo "[flutter_skill_gen] '
          'Post-merge: syncing skill files..."',
        )
        ..writeln('flutter_skill_gen sync --ci || true');
    }

    return buf.toString();
  }

  /// Resolves the `.git/hooks/` directory for a project.
  ///
  /// Returns `null` if the project is not a git repository.
  static String? hooksDir(String projectPath) {
    final gitDir = Directory(p.join(projectPath, '.git'));
    if (!gitDir.existsSync()) return null;
    return p.join(projectPath, '.git', 'hooks');
  }

  /// Installs a single hook. If the hook file already exists
  /// and was not generated by flutter_skill_gen, the existing hook
  /// is preserved with a `.backup` suffix.
  ///
  /// Returns `true` if the hook was installed successfully.
  static bool installHook({
    required String projectPath,
    required String hookName,
  }) {
    if (!supportedHooks.contains(hookName)) return false;

    final dir = hooksDir(projectPath);
    if (dir == null) return false;

    Directory(dir).createSync(recursive: true);

    final hookPath = p.join(dir, hookName);
    final hookFile = File(hookPath);

    // Back up existing hook if it wasn't ours.
    if (hookFile.existsSync()) {
      final existing = hookFile.readAsStringSync();
      if (!existing.contains('Auto-generated by flutter_skill_gen')) {
        final backupPath = '$hookPath.backup';
        hookFile.copySync(backupPath);
      }
    }

    hookFile.writeAsStringSync(hookScript(hookName));

    // Make executable (chmod +x).
    Process.runSync('chmod', ['+x', hookPath]);

    return true;
  }

  /// Installs all supported hooks.
  ///
  /// Returns a map of hook name → success status.
  static Map<String, bool> installAll({required String projectPath}) {
    return {
      for (final hook in supportedHooks)
        hook: installHook(projectPath: projectPath, hookName: hook),
    };
  }

  /// Removes a flutter_skill_gen hook. Only removes hooks that
  /// were generated by this tool. Restores `.backup` if present.
  ///
  /// Returns `true` if the hook was removed.
  static bool removeHook({
    required String projectPath,
    required String hookName,
  }) {
    final dir = hooksDir(projectPath);
    if (dir == null) return false;

    final hookPath = p.join(dir, hookName);
    final hookFile = File(hookPath);

    if (!hookFile.existsSync()) return false;

    final content = hookFile.readAsStringSync();
    if (!content.contains('Auto-generated by flutter_skill_gen')) {
      return false;
    }

    hookFile.deleteSync();

    // Restore backup if present.
    final backupFile = File('$hookPath.backup');
    if (backupFile.existsSync()) {
      backupFile.renameSync(hookPath);
    }

    return true;
  }

  /// Removes all flutter_skill_gen hooks.
  static Map<String, bool> removeAll({required String projectPath}) {
    return {
      for (final hook in supportedHooks)
        hook: removeHook(projectPath: projectPath, hookName: hook),
    };
  }

  /// Checks which hooks are currently installed.
  static Map<String, bool> status({required String projectPath}) {
    final dir = hooksDir(projectPath);
    if (dir == null) {
      return {for (final h in supportedHooks) h: false};
    }

    return {for (final hook in supportedHooks) hook: _isInstalled(dir, hook)};
  }

  static bool _isInstalled(String dir, String hookName) {
    final file = File(p.join(dir, hookName));
    if (!file.existsSync()) return false;
    return file.readAsStringSync().contains(
      'Auto-generated by flutter_skill_gen',
    );
  }
}
