import 'dart:io';

import 'package:path/path.dart' as p;

/// Generates a GitHub Actions workflow for automated skill sync.
class GitHubActionGenerator {
  const GitHubActionGenerator._();

  /// Default workflow file path relative to the project root.
  static const defaultPath = '.github/workflows/skill_sync.yml';

  /// Generates the workflow YAML content.
  ///
  /// [usesFlutter] controls whether the workflow sets up Flutter
  /// SDK (via `subosito/flutter-action`) or just Dart SDK.
  static String generate({bool usesFlutter = true}) {
    final buf = StringBuffer()
      ..writeln('# Auto-generated by flutter_skill_gen')
      ..writeln('# Keeps SKILL.md files in sync on every push.')
      ..writeln('# Docs: https://pub.dev/packages/flutter_skill_gen')
      ..writeln()
      ..writeln('name: Sync SKILL.md')
      ..writeln()
      ..writeln('on:')
      ..writeln('  push:')
      ..writeln('    paths:')
      ..writeln("      - 'lib/**'")
      ..writeln("      - 'pubspec.yaml'")
      ..writeln("      - 'test/**'")
      ..writeln()
      ..writeln('jobs:')
      ..writeln('  sync-skills:')
      ..writeln('    runs-on: ubuntu-latest')
      ..writeln('    steps:')
      ..writeln('      - uses: actions/checkout@v4')
      ..writeln('        with:')
      ..writeln('          token: \${{ secrets.GITHUB_TOKEN }}');

    if (usesFlutter) {
      buf
        ..writeln()
        ..writeln('      - uses: subosito/flutter-action@v2')
        ..writeln('        with:')
        ..writeln('          channel: stable');
    } else {
      buf
        ..writeln()
        ..writeln('      - uses: dart-lang/setup-dart@v1');
    }

    buf
      ..writeln()
      ..writeln('      - name: Install flutter_skill_gen')
      ..writeln('        run: dart pub global activate flutter_skill_gen')
      ..writeln()
      ..writeln('      - name: Sync skill files')
      ..writeln('        run: flutter_skill_gen sync --ci')
      ..writeln('        env:')
      ..writeln(
        '          FLUTTER_SKILL_API_KEY: '
        '\${{ secrets.FLUTTER_SKILL_API_KEY }}',
      )
      ..writeln()
      ..writeln('      - name: Commit changes')
      ..writeln(
        '        uses: stefanzweifel/'
        'git-auto-commit-action@v5',
      )
      ..writeln('        with:')
      ..writeln("          commit_message: 'chore: sync SKILL.md files'")
      ..writeln(
        '          file_pattern: '
        "'*.md .cursorrules .windsurfrules "
        '.github/copilot-instructions.md '
        ".agents/** .gemini/**'",
      );

    return buf.toString();
  }

  /// Writes the workflow file to the project.
  ///
  /// Returns the absolute path of the written file.
  static String write({required String projectPath, bool usesFlutter = true}) {
    final content = generate(usesFlutter: usesFlutter);
    final outputPath = p.join(projectPath, defaultPath);
    final file = File(outputPath);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
    return outputPath;
  }
}
